version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: eladmin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: eladmin
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - eladmin-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:6.0-alpine
    container_name: eladmin-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - eladmin-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: eladmin-app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Shanghai
    networks:
      - eladmin-net
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  eladmin-net:
    driver: bridge